-- MySQL Script generated by MySQL Workbench
-- 06/15/20 12:32:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NULL,
  `model` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_permission` (
  `id` INT NOT NULL,
  `content_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auth_permission_django_content_type_idx` (`content_type_id` ASC),
  CONSTRAINT `fk_auth_permission_django_content_type`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `mydb`.`django_content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NULL,
  `last_login` DATE NULL,
  `is_superuser` TINYINT NULL,
  `username` VARCHAR(150) NULL,
  `first_name` VARCHAR(30) NULL,
  `email` VARCHAR(254) NULL,
  `is_staff` TINYINT NULL,
  `is_active` TINYINT NULL,
  `date_joined` DATETIME NULL,
  `last_name` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_user_user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auth_user_user_permissions_auth_user1_idx` (`user_id` ASC),
  INDEX `fk_auth_user_user_permissions_auth_permission1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_auth_user_user_permissions_auth_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_user_user_permissions_auth_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`auth_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_group_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auth_group_permissions_auth_group1_idx` (`group_id` ASC),
  INDEX `fk_auth_group_permissions_auth_permission1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_auth_group_permissions_auth_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`auth_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_group_permissions_auth_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`auth_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auth_user_groups_auth_user1_idx` (`user_id` ASC),
  INDEX `fk_auth_user_groups_auth_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_auth_user_groups_auth_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_user_groups_auth_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`auth_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME NULL,
  `object_id` TEXT NULL,
  `object_repr` VARCHAR(200) NULL,
  `change_message` TEXT NULL,
  `content_type_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `action_flag` SMALLINT(0) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_django_admin_log_django_content_type1_idx` (`content_type_id` ASC),
  INDEX `fk_django_admin_log_auth_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_django_admin_log_django_content_type1`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `mydb`.`django_content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_django_admin_log_auth_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`app_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_usuario_auth_user1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_app_usuario_auth_user1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_comunicados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`app_comunicados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `descripcion` VARCHAR(50) NULL,
  `documento` VARCHAR(100) NULL,
  `imagen` VARCHAR(100) NULL,
  `fecha_creacion` DATETIME NULL,
  `link` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_mi_comunicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`app_mi_comunicado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comunicados_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_mi_comunicado_app_comunicados1_idx` (`comunicados_id` ASC),
  INDEX `fk_app_mi_comunicado_app_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_app_mi_comunicado_app_comunicados1`
    FOREIGN KEY (`comunicados_id`)
    REFERENCES `mydb`.`app_comunicados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_mi_comunicado_app_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`app_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`app_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `descripcion` VARCHAR(50) NULL,
  `documento` VARCHAR(100) NULL,
  `fecha_creacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_mi_documento_enviado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`app_mi_documento_enviado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `documento_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_mi_documento_enviado_app_documento1_idx` (`documento_id` ASC),
  INDEX `fk_app_mi_documento_enviado_app_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_app_mi_documento_enviado_app_documento1`
    FOREIGN KEY (`documento_id`)
    REFERENCES `mydb`.`app_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_mi_documento_enviado_app_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`app_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`app_mi_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`app_mi_documento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `documento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_app_mi_documento_app_usuarios1_idx` (`usuario_id` ASC),
  INDEX `fk_app_mi_documento_app_documento1_idx` (`documento_id` ASC),
  CONSTRAINT `fk_app_mi_documento_app_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`app_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_app_mi_documento_app_documento1`
    FOREIGN KEY (`documento_id`)
    REFERENCES `mydb`.`app_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
